### ISSUE TITLE
Bug! after uploading, files are defective and larger

### ISSUE THREAD

**Issue by parajbs** [vlad20012/ipfs-webdav#2]
Hello @vlad20012,

i tested the docker version of your "vlad20012/ipfs-webdav".
The connection to the ipfs node worked, and I can also reach the webdav server.

I think it's a great project.

But there are problems, all uploaded files are defective afterwards.
They are on the ipfs node in the mfs, but the size of the files is no longer the same as the original size and even if I download the files via webdav or ipfs, the file size is no longer correct.
They are always bigger than the original.

I compared both files with diff, and it shows that the uploaded files have "0"s inserted in several places.

What's going on there?
I need your help because I don't know the programming language rust myself.

I think if it uploads the files cleanly and works, it's a super top ipfs project.

hopefully you can help.

**Comment by vlad20012** [comment]
Hi! Thank you for your report!
I've managed to reproduce it. It's weird I didn't notice it earlier 😅
I'll try to fix it today

**Comment by vlad20012** [comment]
Fixed by 93d04d23af90393f0ef24dbfa40f88799d2eac26 and released as [0.1.1](https://github.com/vlad20012/ipfs-webdav/releases/tag/0.1.1).

A fun fact is that it was needed to just update dependencies to fix this issue (in other words, the issue has been fixed here - https://github.com/ferristseng/rust-multipart-rfc7578/commit/6959435fbad02cb9fcbe6716d8f60a75866a39ae)

**Comment by parajbs** [comment]
Hello @vlad20012,

Thank you for your quick reaction.
I tested the new version 0.1.1 and it works great.

I have a few questions:
- Do you also know the Golang programming language?
  Since your project would also be interesting for a backend module from "rclone". rclone is written in golang.

- maybe you are interested in writing an ipfs module for "rclone".
I think it's super cool.
maybe it is also possible to integrate rust into rclone? no idea.

your "ipfs-webdav" is definitely a great project.

**Comment by parajbs** [comment]
I'm working with colleagues on the project "s5-dev/S5" where we built a "webdav store module" and testing all possible webdav providers and webdav software.

I will test your "ipfs-webdav" project there with the s5-node, and then add it to our list later, so that our other developers can also use their project for ipfs.

You can have a look at "s5-dev/S5" if you are interested.
